name: Pylint
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Load keys into ssh-agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.GH_ALERTS_USERS_TABLE_NAME }}

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r backend/requirements_test.txt
      - name: Linting code
        env:
          AWS_REGION: 'us-west-2'
          GH_ALERTS_USERS_TABLE_NAME: ${{ secrets.GH_ALERTS_USERS_TABLE_NAME }}
          GH_TOKEN: 'test-token'
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
