name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          python -m pip install -r backend/requirements_test.txt
      - name: Run test suite
        env:
          AWS_REGION: 'us-west-2'
          GH_TOKEN: 'test-token'
        run: |
          source venv/bin/activate
          pytest -v
